### ISSUE TITLE
Could not load the "sharp" module using the win32-x64 runtime

### ISSUE THREAD

**Issue by Markos-Vasalos** [contentauth/c2pa-node#69]
I've installed the c2pa-node library through npm, but as soon as i try to build my node app (i'm using webpack for this), i get the following error: "Could not load the "sharp" module using the win32-x64 runtime". (i'm running on windows 11)

The c2pa-node version currently installed is 0.5.20. 

Thanks a lot in advance!

**Comment by dkozma** [comment]
Hi @Markos-Vasalos, would you be able to post any related logs? I'm seeing some [related issues](https://github.com/lovell/sharp/issues?q=win32-x64) in the sharp module (we had to recently upgrade to the latest version due to an issue we were having on our automation).

Additionally, does `c2pa-node@0.5.19` work for you?

**Comment by Markos-Vasalos** [comment]
Hello @dkozma and thank you for your quick reply!

First of all webpack gives me these warnings (not sure if help)

WARNING in ./node_modules/sharp/lib/libvips.js 60:13-54
Module not found: Error: Can't resolve '@img/sharp-libvips-dev/include' in 'C:\Users\mvasalos\Documents\My-projects\ProjectDenn\code_repos\backend\node_modules\sharp\lib'
 @ ./node_modules/sharp/lib/utility.js 10:32-52
 @ ./node_modules/sharp/lib/index.js 14:0-20
 @ ./node_modules/c2pa-node/dist/js-src/lib/thumbnail.js 15:32-48
 @ ./node_modules/c2pa-node/dist/js-src/index.js 13:20-46
 @ ./src/domain/media/media-service.js 6:0-72 31:15-30 52:25-41 53:17-27
 @ ./src/application/controller/media-controller.js 5:0-59 26:4-13
 @ ./src/application/configuration/routes.js 4:0-61 9:37-52
 @ ./src/index.js 4:0-69 9:0-16

WARNING in ./node_modules/sharp/lib/libvips.js 69:11-54
Module not found: Error: Can't resolve '@img/sharp-libvips-dev/cplusplus' in 'C:\Users\mvasalos\Documents\My-projects\ProjectDenn\code_repos\backend\node_modules\sharp\lib'
 @ ./node_modules/sharp/lib/utility.js 10:32-52
 @ ./node_modules/sharp/lib/index.js 14:0-20
 @ ./node_modules/c2pa-node/dist/js-src/lib/thumbnail.js 15:32-48
 @ ./node_modules/c2pa-node/dist/js-src/index.js 13:20-46
 @ ./src/domain/media/media-service.js 6:0-72 31:15-30 52:25-41 53:17-27
 @ ./src/application/controller/media-controller.js 5:0-59 26:4-13
 @ ./src/application/configuration/routes.js 4:0-61 9:37-52
 @ ./src/index.js 4:0-69 9:0-16

WARNING in ./node_modules/sharp/lib/sharp.js 24:12-25
Critical dependency: the request of a dependency is an expression
 @ ./node_modules/sharp/lib/constructor.js 10:0-18
 @ ./node_modules/sharp/lib/index.js 6:14-38
 @ ./node_modules/c2pa-node/dist/js-src/lib/thumbnail.js 15:32-48
 @ ./node_modules/c2pa-node/dist/js-src/index.js 13:20-46
 @ ./src/domain/media/media-service.js 6:0-72 31:15-30 52:25-41 53:17-27
 @ ./src/application/controller/media-controller.js 5:0-59 26:4-13
 @ ./src/application/configuration/routes.js 4:0-61 9:37-52
 @ ./src/index.js 4:0-69 9:0-16

WARNING in ./node_modules/sharp/lib/utility.js 72:17-54
Module not found: Error: Can't resolve '@img/sharp-wasm32/versions' in 'C:\Users\mvasalos\Documents\My-projects\ProjectDenn\code_repos\backend\node_modules\sharp\lib'
 @ ./node_modules/sharp/lib/index.js 14:0-20
 @ ./node_modules/c2pa-node/dist/js-src/lib/thumbnail.js 15:32-48
 @ ./node_modules/c2pa-node/dist/js-src/index.js 13:20-46
 @ ./src/domain/media/media-service.js 6:0-72 31:15-30 52:25-41 53:17-27
 @ ./src/application/controller/media-controller.js 5:0-59 26:4-13
 @ ./src/application/configuration/routes.js 4:0-61 9:37-52
 @ ./src/index.js 4:0-69 9:0-16


And ends up with: 

webpack 5.90.1 compiled with 23 warnings in 2282 ms
webpack-internal:///./node_modules/sharp/lib/sharp.js:114
  throw new Error(help.join('\n'));
  ^

Error: Could not load the "sharp" module using the win32-x64 runtime
Possible solutions:
- Ensure optional dependencies can be installed:
    npm install --include=optional sharp
    yarn add sharp --ignore-engines
- Ensure your package manager supports multi-platform installation:
    See https://sharp.pixelplumbing.com/install#cross-platform
- Add platform-specific dependencies:
    npm install --os=win32 --cpu=x64 sharp
- Consult the installation documentation:
    See https://sharp.pixelplumbing.com/install
    at eval (webpack-internal:///./node_modules/sharp/lib/sharp.js:114:9)
    
I've tried various solutions like installing sharp separately or using specific --os and --cpu flags like the ones specified above but  the issue persists. If you need specific logs let me know.

**Comment by dkozma** [comment]
I'm thinking it _may_ have to do with this change: https://github.com/lovell/sharp/issues/3750

Which package manager are you using? I see that the author recommends the latest version of `yarn` if you are using that by any chance.

**Comment by Markos-Vasalos** [comment]
Unfortunately i'm only using npm, version 10.4.0 and my node is 20.10.0

**Comment by Markos-Vasalos** [comment]
Any update on the above?

**Comment by SteveMaier-IRT** [comment]
You can also have it run using this optional version of sharp.  Made it work for me locally on my Win64 machine.

`npm i @img/sharp-win32-x64 --save-optional`

**Comment by dkozma** [comment]
Hi @Markos-Vasalos, I'm not used to seeing Node packages being used with Webpack that often, so I'm not sure what its doing under the hood, however I wonder if it is trying to post-process some of the packages and causing issues.

What happens if you try to add `sharp` to the externals as mentioned here? https://sharp.pixelplumbing.com/install#webpack

**Comment by Markos-Vasalos** [comment]
@SteveMaier-IRT tried it but unfortunately it doesn't work with webpack

@dkozma Tried it and it changed the error. Now it complaints that it cannot find the module. Surely webpack does optimizations in dependencies under the hood so it probably breaks something. I might work with a different bundler if necessary instead of webpack. Thank you very much for your effort so far

**Comment by joshh20** [comment]
Also experiencing this issue. Did you ever figure out a solution?

**Comment by Markos-Vasalos** [comment]
@joshh20 I just stopped using webpack unfortunately. It wasn't necessary for my project eventually.

**Comment by joshh20** [comment]
@Markos-Vasalos Thank you.
